### ISSUE TITLE
Where are you importing this type from

### ISSUE THREAD

**Issue by pablo-clueless** [Zummit-Africa-Inc/Zapi-FE#33]
https://github.com/Zummit-Africa-Inc/Zapi-FE/blob/e91ddacfb9f36380fae757499b9bcbd553a45e56/src/components/Map.tsx#L4

**Comment by CreedTech** [comment]
I'm creating an interface so i can use it on that page for the map component 
No map importing was done there, Was done on the other page @pablo-clueless
